name: Build and test for Apple iOS swift

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - '**spm**'
      - '**swift**'
  pull_request:
    paths:
      - '**spm**'
      - '**swift**'

jobs:
  swift-build-run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Preparing Swift Build
      run: |
        mkdir -p spm_headers/nanopb
        cp pb.h pb_common.h pb_decode.h pb_encode.h spm_headers/nanopb/
    - name: Build
      run: swift build
    - name: Run
      run: swift test
