name: spm

on:
  [push, pull_request]:
    paths:
    - '.github/workflows/spm.yml'
    - 'Package.swift'
    - '*.[ch]'

jobs:
  swift-build-run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run
      run: swift run
